set hidden
set termguicolors
set background=dark
set number
set relativenumber
set cursorline
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set incsearch
set clipboard=unnamedplus
set nowrap
set mouse=a
set smartindent
set cmdheight=2
set noshowmode
set ignorecase
set nosmartcase
set nobackup
set noswapfile
set nowritebackup

